# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

# Shared secrets are available across all environments.

# shared:
#   api_key: a1B2c3D4e5F6

# Environmental secrets are only available for that specific environment.

development:
  secret_key_base: 9ae68d79ff95216d1931f69e7f4577cdfca4f6a71662989d1434a5a5585f7120e97ffa01e09cbb877e7269716295edbd19dba5d59eaec80334d27a35d52088bc

test:
  secret_key_base: 3208489401af49a03666c28f5172ae2f51e8a4fa54141943759047f3d469cefa8eed1f544c9186ffa475b1c92df160e88f020a8c52916b6725516eb7a78ab355

# Do not keep production secrets in the unencrypted secrets file.
# Instead, either read values from the environment.
# Or, use `bin/rails secrets:setup` to configure encrypted secrets
# and move the `production:` environment over there.

production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
